### ISSUE TITLE
"unhandled event" printed on screen

### ISSUE THREAD

**Issue by th-otto** [mfro0/libcmini-examples#1]
When running the bench program from Gemini, i get an "unhandled event 4700" printed on the screen (corrupting the menu line). This is an AV_PROTOKOLL request from Gemini.

Edit: maybe i was wrong, and the message was not sent by gemini, but by some accessory. Still, that debug message should not go to the screen.

**Comment by mfro0** [comment]
fixed with 9d02ea6 (printout changed to a debug diagnostic message now)
