### ISSUE TITLE
vqt_name may fill the whole array of 32 chars

### ISSUE THREAD

**Issue by th-otto** [mfro0/libcmini-examples#2]
In your calls to vqt_name(), the array is only 32 chars. The VDI does not neccarily terminate that with a traling '\0' if the fontname is 32 chars or longer, causing crashes:

DEBUG: (init_fontwindow):font 51="Wingdings 2 Regular"
DEBUG: (init_fontwindow):font 52="Bitstream Vera Sans Mono Bold ObM´P\ק`cXצb°"
DEBUG: (init_fontwindow):font 53="Palatino Linotype Italic"

The program displays some more garbled font names, then crashes.

Attached is a patch for this

[vqt_name.patch.txt](https://github.com/mfro0/libcmini-examples/files/4638327/vqt_name.patch.txt)

Edit: see also  [binding in gemlib](https://github.com/freemint/gemlib/blob/ef2c4dbaca8ee5bac6e8c69f844924b672344c6d/vqt_name.c#L23); it explicitly copies 33 chars (last one being a flag IIRC)

There are also some redraw problems with the font window, when i resize it in aranym:

![Screenshot_20200516_142228](https://user-images.githubusercontent.com/12425871/82119687-dd24b580-9780-11ea-9595-37fb0d2a5c48.png)

When i resize it, i can briefly see some text being printed at the edges, but shortly after the whole window is filled with a white background.

**Comment by mfro0** [comment]
should be fixed with 52bcc0e . While at it, window scrolling was implemented as well. Thank you!
